import { StyleSheet } from "react-native";
import { themes } from "../../global/themes";

export const style = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: themes.colors.background,
  },
  header: {
    backgroundColor: themes.colors.primary,
    paddingTop: 60,
    paddingBottom: 20,
    paddingHorizontal: themes.spacing.lg,
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
    elevation: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
  },
  headerTitle: {
    fontSize: themes.typography.fontSize.header,
    fontWeight: themes.typography.fontWeight.bold,
    color: themes.colors.surface,
  },
  content: {
    flex: 1,
    padding: themes.spacing.lg,
    alignItems: "center",
    justifyContent: "center",
  },
  taskIndicator: {
    backgroundColor: themes.colors.surface,
    padding: themes.spacing.md,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: themes.colors.border,
    width: "100%",
    marginBottom: 40,
    alignItems: "center",
  },
  taskLabel: {
    fontSize: themes.typography.fontSize.small,
    color: themes.colors.textLight,
    textTransform: "uppercase",
    letterSpacing: 1,
    marginBottom: 4,
  },
  taskTitle: {
    fontSize: themes.typography.fontSize.title,
    fontWeight: themes.typography.fontWeight.bold,
    color: themes.colors.primary,
    textAlign: "center",
  },
  timerContainer: {
    alignItems: "center",
    justifyContent: "center",
    width: 250,
    height: 250,
    borderRadius: 125,
    borderWidth: 8,
    borderColor: themes.colors.secondary,
    backgroundColor: themes.colors.surface,
    marginBottom: 40,
    elevation: 6,
    shadowColor: themes.colors.secondary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
  },
  timerText: {
    fontSize: 64,
    fontWeight: themes.typography.fontWeight.bold,
    color: themes.colors.text,
    fontVariant: ["tabular-nums"],
  },
  controlsContainer: {
    flexDirection: "row",
    justifyContent: "space-evenly",
    width: "100%",
    paddingHorizontal: themes.spacing.lg,
  },
  controlButton: {
    width: 64,
    height: 64,
    borderRadius: 32,
    alignItems: "center",
    justifyContent: "center",
    elevation: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
  buttonPrimary: {
    backgroundColor: themes.colors.primary,
  },
  buttonSecondary: {
    backgroundColor: themes.colors.surface,
    borderWidth: 1,
    borderColor: themes.colors.border,
  },
  buttonDanger: {
    backgroundColor: themes.colors.error || "#FF5252",
  },
});
