import { StyleSheet } from "react-native";
import { themes } from "../../global/themes";

export const style = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: themes.colors.background,
  },
  header: {
    backgroundColor: themes.colors.primary,
    paddingTop: 60,
    paddingBottom: 20,
    paddingHorizontal: themes.spacing.lg,
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
    elevation: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
  },
  profileContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: themes.spacing.md,
  },
  avatar: {
    width: 50,
    height: 50,
    borderRadius: 25,
    borderWidth: 2,
    borderColor: themes.colors.secondary,
    marginRight: themes.spacing.md,
  },
  headerTitle: {
    fontSize: themes.typography.fontSize.header,
    fontWeight: themes.typography.fontWeight.bold,
    color: themes.colors.surface,
  },
  headerSubtitle: {
    fontSize: themes.typography.fontSize.small,
    color: themes.colors.border,
    marginTop: 2,
  },
  content: {
    flex: 1,
    padding: themes.spacing.lg,
  },
  sectionTitle: {
    fontSize: themes.typography.fontSize.title,
    fontWeight: themes.typography.fontWeight.bold,
    color: themes.colors.text,
    marginBottom: themes.spacing.md,
    marginTop: themes.spacing.sm,
  },
  cardRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: themes.spacing.lg,
  },
  statsCard: {
    flex: 1,
    backgroundColor: themes.colors.surface,
    borderRadius: 12,
    padding: themes.spacing.md,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: themes.colors.border,
    marginHorizontal: 4,
  },
  statsValue: {
    fontSize: 24,
    fontWeight: themes.typography.fontWeight.bold,
    marginTop: 8,
  },
  statsLabel: {
    fontSize: themes.typography.fontSize.small,
    color: themes.colors.textLight,
    marginTop: 4,
  },
  taskWidget: {
    backgroundColor: themes.colors.secondary,
    borderRadius: 12,
    padding: themes.spacing.md,
    flexDirection: "row",
    alignItems: "center",
    marginBottom: themes.spacing.lg,
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  taskWidgetText: {
    color: themes.colors.surface,
    fontSize: themes.typography.fontSize.regular,
    fontWeight: themes.typography.fontWeight.bold,
    marginLeft: themes.spacing.sm,
  },
  readmeContainer: {
    backgroundColor: themes.colors.surface,
    borderRadius: 12,
    padding: themes.spacing.md,
    borderWidth: 1,
    borderColor: themes.colors.border,
    marginBottom: themes.spacing.lg,
    maxHeight: 250, // Permite que o README longo crie um scroll interno
  },
  readmeText: {
    fontSize: themes.typography.fontSize.regular,
    color: themes.colors.textLight,
    lineHeight: 22,
  },
  actionCard: {
    flexDirection: "row",
    backgroundColor: themes.colors.surface,
    borderRadius: 12,
    padding: themes.spacing.md,
    marginBottom: themes.spacing.md,
    borderWidth: 1,
    borderColor: themes.colors.border,
    alignItems: "center",
  },
  actionIconContainer: {
    backgroundColor: themes.colors.background,
    padding: themes.spacing.md,
    borderRadius: 50,
    marginRight: themes.spacing.md,
  },
  actionTextContainer: {
    flex: 1,
  },
  actionTitle: {
    fontSize: themes.typography.fontSize.regular,
    fontWeight: themes.typography.fontWeight.bold,
    color: themes.colors.text,
  },
  actionDescription: {
    fontSize: themes.typography.fontSize.small,
    color: themes.colors.textLight,
    marginTop: 4,
  },
});
